### ISSUE TITLE
Socket.io version ?

### ISSUE THREAD

**Issue by DouglasHennrich** [appcelerator-modules/titanium-socketio#2]
Which version of socket.io this module supports?
Great module, btw.
 Currently I'm using `net.iamyellow.tiws` which support `1.4.5` fixed for titanium use

**Comment by hansemannn** [comment]
Latest (13.2.0) from the [socket.io-client-swift](https://github.com/socketio/socket.io-client-swift) for iOS. Android is still in development and will be open sourced next. It is used internally already, so you should give it a try!
